SELECT * FROM "USER";
SELECT ID, PW FROM "USER" WHERE ID = 'joon4141';

--ALTER SEQUENCE 시퀸스명 INCREMENT BY -(마지막 값 -1);
--SELECT 시퀸스명.NEXTVAL FROM DUAL;
--ALTER SEQENCE 시퀸스명 INCREMENT BY 1;
-- 걍 드랍하는게 편하다.