--DML(DELETE, UPDATE)실습

--PLAYER 테이블에서 TEAM_ID가 'K01'인 선수 이름을 내이름으로 바꾸기
--ROLLBACK
UPDATE PLAYER 
SET PLAYER_NAME = '김휘준'
WHERE TEAM_ID = 'K01'

SELECT * FROM PLAYER WHERE TEAM_ID ='K01';

--PALYER 테이블에서 POSITION이 'MF'인 선수 삭제하기
--ROLLBACK
DELETE FROM PLAYER
WHERE "POSITION" = 'MF'

SELECT * FROM PLAYER WHERE "POSITION" = 'MF';

--PLAYER 테이블에서 HEIGHT가 180이상인 선수 삭제하기
--ROLLBACK
DELETE FROM PLAYER WHERE HEIGHT >= 180;
SELECT * FROM PLAYER WHERE HEIGHT >= 180;
